Fixed missing ;; in pull script.

diff --git a/pull b/pull
--- a/pull
+++ b/pull
@@ -4,17 +4,18 @@ set -e
 dir=
 case $1 in
     manager|service-manager)
-	dir=/var/lib/downlaods/service-manager
-	;;
+		dir=/var/lib/downlaods/service-manager
+		;;
     scripts) 
-	dir=/var/lib.downloads/scripts 
-	;;
+		dir=/var/lib.downloads/scripts 
+		;;
     groovlets)
-	dir=/var/lib/groovlets
+		dir=/var/lib/groovlets
+		;;
     *)
-	echo "Invalid directory"
-	exit 1
-	;;
+		echo "Invalid directory"
+		exit 1
+		;;
 esac
 set -u
 
